apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app: sample-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: sample-api:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: sample-api-config
                  key: APP_VERSION
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sample-api-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi