apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: sample-api-config
    literals:
      - APP_VERSION=0.1.0-kind
      - LOG_LEVEL=info