apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  template:
    spec:
      containers:
        - name: sample-api
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi