apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: sample-api-config
    behavior: merge
    literals:
      - LOG_LEVEL=info

patches:
  - path: replicas.yaml
  - path: resources.yaml
  - path: ingress-host.yaml
    target:
      kind: Ingress
      name: sample-api